CREATE TABLE TOPIC(
    TOPIC_ID BIGSERIAL PRIMARY KEY ,
    TOPIC_TITLE VARCHAR(200) NOT NULL,
);
CREATE TABLE SUBTOPIC(
    SUBTOPIC_ID BIGSERIAL PRIMARY KEY,
    SUBTOPIC_TITLE VARCHAR(200) NOT NULL,
    TOPIC_ID BIGINT NOT NULL REFERENCES TOPIC(TOPIC_ID)
);
CREATE TABLE QUIZ(
    QUIZE_ID BIGSERIAL PRIMARY KEY,
    QUESTION VARCHAR(400) NOT NULL,
    ANSWER VARCHAR(400) NOT NULL,
    ISREMEMBERED INTEGER,
    SUBTOPIC_ID BIGINT NOT NULL REFERENCES SUBTOPIC(SUBTOPIC_ID)
);

INSERT INTO TOPIC (TOPIC_TITLE) VALUES ('ENGLISH');
INSERT INTO TOPIC (TOPIC_TITLE) VALUES ('PROGRAMMING');
INSERT INTO TOPIC (TOPIC_TITLE) VALUES ('CHEMISTRY');

INSERT INTO SUBTOPIC (SUBTOPIC_TITLE, TOPIC_ID) VALUES ('COLOR', 1);
INSERT INTO SUBTOPIC (SUBTOPIC_TITLE, TOPIC_ID) VALUES ('ANIMAL', 1);
INSERT INTO SUBTOPIC (SUBTOPIC_TITLE, TOPIC_ID) VALUES ('VEGETABLES', 1);

INSERT INTO SUBTOPIC (SUBTOPIC_TITLE, TOPIC_ID) VALUES ('JAVA', 2);
INSERT INTO SUBTOPIC (SUBTOPIC_TITLE, TOPIC_ID) VALUES ('C', 2);
INSERT INTO SUBTOPIC (SUBTOPIC_TITLE, TOPIC_ID) VALUES ('PYTHON', 2);

INSERT INTO SUBTOPIC (SUBTOPIC_TITLE, TOPIC_ID) VALUES ('ORGANIC', 3);
INSERT INTO SUBTOPIC (SUBTOPIC_TITLE, TOPIC_ID) VALUES ('INORGANIC', 3);

INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('RED','КРАСНЫЙ', 0, 1);
INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('BLACK','ЧЕРНЫЙ', 0, 1);
INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('YELLOW','ЖЕЛТЫЙ', 0, 1);

INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('DOG','СОБАКА', 1, 2);
INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('CAT','КОТ', 1, 2);
INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('HORSE','ЛОШАДЬ', 0, 2);

INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('TOMATO','ТОМАТ', 0, 3);
INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('POTATO','КАРТОФЕЛЬ', 0, 3);
INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('PEPPER','ПЕРЕЦ', 0, 3);

INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('ARRAY','МАССИВ', 0, 4);
INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('LIST','ЛИСТ', 0, 4);
INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('ABSTRACTION','АБСТРАКЦИЯ', 0, 4);

INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('REFERENCE','ССЫЛКА', 0, 5);
INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('STRUCT','СТРУКТУРА', 0, 5);
INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('EOF','КОНЕЦ ФАЙЛА', 0, 5);

INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('С2H5OH','СПИРТ', 0, 7);
INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('H2O','ВОДА', 0, 7);

INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('H2','ВОДОРОД', 0, 8);
INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('Au','ЗОЛОТО', 0,8);
INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('Na','НАТРИЙ', 0, 8);
INSERT INTO QUIZ (QUESTION, ANSWER, ISREMEMBERED, SUBTOPIC_ID) VALUES ('Zn','ЦИНК', 0, 8);


SELECT * FROM TOPIC;
SELECT * FROM SUBTOPIC
WHERE TOPIC_ID = 1;
SELECT * FROM QUIZ q
WHERE q.ISREMEMBERED = 1
SELECT COUNT(*) FROM QUIZ
WHERE ISREMEMBERED = 1;

SELECT t.TOPIC_TITLE, st.SUBTOPIC_TITLE, COUNT(q.QUESTION) AS TOTAL_QUESTIONS
FROM TOPIC t
         LEFT JOIN SUBTOPIC st on t.TOPIC_ID = st.TOPIC_ID
         LEFT JOIN QUIZ Q on st.SUBTOPIC_ID = Q.SUBTOPIC_ID
GROUP BY t.TOPIC_TITLE, st.SUBTOPIC_TITLE
ORDER BY TOPIC_TITLE;
SELECT t.TOPIC_TITLE, st.SUBTOPIC_TITLE, COUNT(q.ISREMEMBERED) AS READY
FROM TOPIC t
         LEFT JOIN SUBTOPIC st on t.TOPIC_ID = st.TOPIC_ID
         LEFT JOIN QUIZ Q on st.SUBTOPIC_ID = Q.SUBTOPIC_ID
WHERE q.ISREMEMBERED = 1
GROUP BY t.TOPIC_TITLE, st.SUBTOPIC_TITLE
ORDER BY TOPIC_TITLE