CREATE TABLE TOPIC(
    TOPIC_ID INTEGER PRIMARY KEY ,
    TOPIC_TITLE VARCHAR(200) NOT NULL,
);
CREATE TABLE SUBTOPIC(
    SUBTOPIC_ID INTEGER PRIMARY KEY,
    SUBTOPIC_TITLE VARCHAR(200) NOT NULL,
    TOPIC_ID INTEGER REFERENCES TOPIC(TOPIC_ID)
);
CREATE TABLE QUIZ(
    QUIZE_ID INTEGER PRIMARY KEY,
    QUESTION VARCHAR(400) NOT NULL,
    ANSWER VARCHAR(400) NOT NULL,
    ISREMEMBERED INTEGER,
    SUBTOPIC_ID INTEGER REFERENCES SUBTOPIC(SUBTOPIC_ID)
)